import type { FunctionComponent } from "react";
import { useState } from "react";
import { Button } from "~/design-system";

export const Waitlist: FunctionComponent = () => {
  const [email, setEmail] = useState<string>();
  const [accessRequested, setAccessRequested] = useState<boolean>(false);

  const emailRegex = new RegExp(".+@.+\\..+");
  const isValidEmail = emailRegex.test(email ?? "");

  const requestAccess = async () => {
    setAccessRequested(false);

    const response = await fetch("https://api.semiprose.syzible.com/waitlist", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ email }),
    });

    setAccessRequested(response.ok);
  };

  return (
    <div className={"h-screen w-screen flex flex-col"}>
      <div className={"flex h-screen"}>
        <div className={"flex flex-col flex-1 bg-purple-50 justify-between"}>
          <h3 className={"p-4 font-bold text-4xl"}>{"Semiprose"}</h3>
          <div className={"w-[350px] self-center px-4"}>
            <img src={"/opinions.svg"} alt={"Inspiration"} />
          </div>
        </div>
        <div className={"flex flex-[2] items-center m-8"}>
          <div className={"flex flex-col gap-4 max-w-screen-md"}>
            <h1 className={"font-medium text-4xl"}>Join the waitlist</h1>
            <p className={"leading-relaxed"}>
              Ignite your writing superpowers with Semiprose 🚀
            </p>
            <ul className={"flex flex-col gap-4"}>
              <li>
                <h3>✨AI-Generated Prompts</h3>
                <p className={"leading-relaxed"}>
                  Embark on writing adventures with unique and inspiring prompts
                  generated by cutting-edge AI. From mystical realms to untold
                  mysteries, our prompts are designed to ignite your
                  imagination.
                </p>
              </li>
              <li>
                <h3>✏️ Weekly Short Story Challenges</h3>
                <p className={"leading-relaxed"}>
                  Challenge yourself and fellow writers with our weekly writing
                  prompts. Engage with the community, explore different genres,
                  and hone your storytelling skills.
                </p>
              </li>
              <li>
                <h3>📚 Interactive Reading Experience</h3>
                <p className={"leading-relaxed"}>
                  Dive into captivating short stories written by talented
                  authors. Express your appreciation with a range of reactions
                  and be part of a supportive community of readers.
                </p>
              </li>
            </ul>
            <div className={"flex gap-4"}>
              <input
                type={"email"}
                className={"border border-gray-200 rounded-xl p-4 flex-1"}
                placeholder={"Your email"}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <Button
                disabled={!isValidEmail}
                label={"Get access"}
                onClick={requestAccess}
              />
            </div>
            <div>
              {accessRequested ? <p>You've been added successfully</p> : null}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
